### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by lat**
We need a couple of simple code changes to get igprof to build with our compilers.

### CODE REVIEW

**Comment by ktf** [comment]
Dear @lat, thanks and welcome back to igprof-land! :-)

The automatic tests on travis-ci fail:

https://travis-ci.org/igprof/igprof/builds/64277968

Can you think of a proper cleanup, or you'd rather mask the warning? If I understand correctly Travis, by default, runs with vanilla "Ubuntu 12.04 LTS Server Edition 64" default GCC.

**Comment by lat** [comment]
I don't have a good suggestion; one compiler (version?) is unhappy with the attribute, another without it. Masking the warning sounds lesser of two evils to me, though I wonder if it's possible to mask it only for that one file (or even source line)? Does it build without masking in CMS? Also, any ideas how would we know when to remove the warning filter in the future?

**Comment by ktf** [comment]
Yes, CMS one is happy without. If urgent, I can merge your changes and see
what are the alternatives next week.

**Comment by ktf** [comment]
Merging this, as agreed. Will look later how to keep travis happy.

**Pull request merged**
